### ISSUE TITLE
Object "Dotpulse\GeoIP\HttpComponent\DotpulseGeoIPUpdateCookieHTTPComponent" is not registered.

### ISSUE THREAD

**Issue by tmotyl** [webexcess/dotpulse-neos-package-geoip#1]
After installing the module in neos 2.3

An error is thrown:
#1264589155: Object "Dotpulse\GeoIP\HttpComponent\DotpulseGeoIPUpdateCookieHTTPComponent" is not registered.
TYPO3\Flow\Object\Exception\UnknownObjectException thrown in file
Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Object/ObjectManager.php in line 201.
Reference code: 2017110312214639ab7f

**Comment by sbruggmann** [comment]
Hi @tmotyl,

Try to rescan the packages: `flow flow:package:rescan`
If this does not help, send the detailed exception `Data/Logs/Exceptions/{Reference_code}.txt` please.

But attention: This package is kind of hardcoded for the two dimensions language and country, and should only be used as a code base to create a project-specific package.
